### PR TITLE
Include data/*.dat in the installed package

### PR DESCRIPTION
**Pull request by jbarnoud**
Also remove the MANIFEST.in for now as it is redundant with setup.py.

### CODE REVIEW

**Comment by jbarnoud** [comment]
You merge too fast! I forgot a file in my fix.

**Comment by Tsjerk** [comment]
You add files too slowly!

**Comment by Tsjerk** [comment]
Oh, and the lipids.dat was not yet in the data folder... So the setup should have '*.dat' at this point or the file has to move.

**Comment by jbarnoud** [comment]
Yes! That is the file I forgot, and that the tests pointed out :wink: There is an other PR to fix that; but wait for the tests to pass before you merge it.

**Pull request merged**
